### ISSUE TITLE
Data availability

### ISSUE THREAD

**Issue by patzaw** [gersteinlab/PsychENCODE_SingleCell_Integrative#3]
Hello

Thank you for this invaluable resource. It's gold.

I wanted to let you know that the following files are not available for download:

- https://brainscope.gersteinlab.org/data/c2c_network/SZBD-Kellis_annotated-SCZ_CON.h5seurat.gz
- https://brainscope.gersteinlab.org/data/LNCTP_perturbation/perturbation_crispr.zip
- All the files in: https://brainscope.gersteinlab.org/data_dir_candidate_SNPs_for_QTL_calls.html

Thank you again

Patrice

**Comment by prashantemani** [comment]
Thank you, Patrice, for letting us know. We are evaluating these links and will update you once they are active again.

**Comment by prashantemani** [comment]
Hi Patrice, We have been able to resolve those links. Please try them again and let us know if you have any issues.

**Comment by patzaw** [comment]
Hi Prashant

I could download the files.

Thank you

Patrice
