### ISSUE TITLE
Some highly expressed genes were filtered out from the pseudo-bulk normalized expression values

### ISSUE THREAD

**Issue by patzaw** [gersteinlab/PsychENCODE_SingleCell_Integrative#4]
Hi,

I recomputed pseudo-bulk counts per cell type starting from the counts you provided in [the annotated matrices](https://brainscope.gersteinlab.org/output-sample-annotated-matrix.html).

I found a few hundred genes that are well expressed but are not present in any of your [pseudo-bulk matrices](https://brainscope.gersteinlab.org/output-pseudobulk-expr.html).

Here are the top 20 genes that I found highly expressed in the samples but are not present in your pseudo-bulk matrices:
IL1RAPL1, FTX, DMD, LINC00632, DANT2, ATRX, TTTY14, AL008633.1, GPM6B, LINC01278, NLGN4Y, HDAC8, USP9Y, TSPAN7, IDS, CDKL5, UTY, JPX, CASK, DIAPH2.

Do you know why they have been filtered out? I believe they pass your filtering criteria described in the Methods and Materials, but I might have missed something.

Thank you,

Patrice

**Comment by prashantemani** [comment]
Hi Patrice,
That is an interesting observation. I have reached out to my colleague who worked on those matrices, and will try to have a conversation with him before I get back to you.
Best,
Prashant

**Comment by prashantemani** [comment]
Hi Patrice,
My colleague Declan looked into this carefully: All the genes you mentioned are on the X or Y chromosomes, which were not analyzed in the associated QTL study. That is why you were unable to find them. 
Hope this helps!
Prashant

**Comment by patzaw** [comment]
Hi Prashant

Thank you for this information. It does help indeed. Maybe you could add this info to the description of the file for future users.

Thanks again

Patrice
